# Generated by Django 6.0.3 on 2026-05-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Колдонуучунун аты')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Баасы (Жылдыз)')),
                ('text', models.TextField(verbose_name='Пикир / Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Кошулган убактысы')),
            ],
            options={
                'verbose_name': 'Пикир',
                'verbose_name_plural': 'Пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
