# Generated by Django 6.0.3 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Баасы'),
        ),
    ]
