# Generated by Django 6.0.3 on 2026-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Башкы сөз (мис: Биз жөнүндө)')),
                ('description', models.TextField(verbose_name='Компания жөнүндө толук текст')),
                ('stat_clients', models.CharField(default='500+', max_length=50, verbose_name='Кардарлардын саны')),
                ('stat_tours', models.CharField(default='50+', max_length=50, verbose_name='Турлардын саны')),
                ('stat_experience', models.CharField(default='5+', max_length=50, verbose_name='Жылдык тажрыйба')),
                ('map_iframe_url', models.TextField(verbose_name='Гугл картанын iframe шилтемеси (src ичиндеги гана)')),
            ],
            options={
                'verbose_name': 'Биз жөнүндө маалымат',
                'verbose_name_plural': 'Биз жөнүндө маалыматтар',
            },
        ),
    ]
