# Generated by Django 6.0.3 on 2026-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='fact_1_icon',
            field=models.CharField(default='🏔️', max_length=50, verbose_name='Факт 1 иконка'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_1_number',
            field=models.CharField(default='500+', max_length=50, verbose_name='Факт 1 сан'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_1_text',
            field=models.TextField(default='Раз мы поднимались на вершины Тянь-Шаня с нашими туристами.', verbose_name='Факт 1 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_2_icon',
            field=models.CharField(default='☕', max_length=50, verbose_name='Факт 2 иконка'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_2_number',
            field=models.CharField(default='2000+', max_length=50, verbose_name='Факт 2 сан'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_2_text',
            field=models.TextField(default='Литров горного чая выпито у костра во время наших походов.', verbose_name='Факт 2 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_3_icon',
            field=models.CharField(default='🚐', max_length=50, verbose_name='Факт 3 иконка'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_3_number',
            field=models.CharField(default='150к', max_length=50, verbose_name='Факт 3 сан'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_3_text',
            field=models.TextField(default='Километров проехали наши джипы по самым диким тропам.', verbose_name='Факт 3 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_4_icon',
            field=models.CharField(default='🤝', max_length=50, verbose_name='Факт 4 иконка'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_4_number',
            field=models.CharField(default='0', max_length=50, verbose_name='Факт 4 сан'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fact_4_text',
            field=models.TextField(default='Скрытых комиссий. Мы за честный и открытый туризм.', verbose_name='Факт 4 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='principle_1_desc',
            field=models.TextField(default='Вы для нас не просто клиент, вы — наш гость. А гость в Кыргызстане — это святое.', verbose_name='Принцип 1 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='principle_1_title',
            field=models.CharField(default='Душевный подход', max_length=100, verbose_name='Принцип 1 аталышы'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='principle_2_desc',
            field=models.TextField(default='Собственный автопарк и опытные гиды со стажем более 10 лет.', verbose_name='Принцип 2 текст'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='principle_2_title',
            field=models.CharField(default='Надежность', max_length=100, verbose_name='Принцип 2 аталышы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='map_iframe_url',
            field=models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2924.1234567890123!2d73.00000000000001!3d42.00000000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1234567890abcdef%3A0xabcdef1234567890!2sManas%20Travel%20Office!5e0!3m2!1sen!2skg!4v1700000000000', verbose_name='Гугл картанын iframe шилтемеси (src ичиндеги гана)'),
        ),
    ]
