# Generated by Django 6.0.3 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutus_fact_1_icon_aboutus_fact_1_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='fact_1_icon',
            field=models.CharField(max_length=50, verbose_name='Факт 1 иконка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_1_number',
            field=models.CharField(max_length=50, verbose_name='Факт 1 сан'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_1_text',
            field=models.TextField(verbose_name='Факт 1 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_2_icon',
            field=models.CharField(max_length=50, verbose_name='Факт 2 иконка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_2_number',
            field=models.CharField(max_length=50, verbose_name='Факт 2 сан'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_2_text',
            field=models.TextField(verbose_name='Факт 2 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_3_icon',
            field=models.CharField(max_length=50, verbose_name='Факт 3 иконка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_3_number',
            field=models.CharField(max_length=50, verbose_name='Факт 3 сан'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_3_text',
            field=models.TextField(verbose_name='Факт 3 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_4_icon',
            field=models.CharField(max_length=50, verbose_name='Факт 4 иконка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_4_number',
            field=models.CharField(max_length=50, verbose_name='Факт 4 сан'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fact_4_text',
            field=models.TextField(verbose_name='Факт 4 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='principle_1_desc',
            field=models.TextField(verbose_name='Принцип 1 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='principle_1_title',
            field=models.CharField(max_length=100, verbose_name='Принцип 1 аталышы'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='principle_2_desc',
            field=models.TextField(verbose_name='Принцип 2 текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='principle_2_title',
            field=models.CharField(default='Надежность', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=200, verbose_name=' Биз жөнүндө'),
        ),
    ]
