# Generated by Django 6.0.3 on 2026-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(verbose_name='Компания жөнүндө кыскача текст (футердеги)')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон номур (мис: +996 553 414 929)')),
                ('address', models.CharField(max_length=255, verbose_name='Дарек (мис: Жалал-Абад ш., Ленин көчөсү)')),
                ('work_hours', models.CharField(max_length=150, verbose_name='Иштөө убактысы')),
                ('instagram_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Инстаграм шилтемеси (URL)')),
                ('whatsapp_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Ватсап шилтемеси (URL)')),
            ],
            options={
                'verbose_name': 'Футер маалыматы',
                'verbose_name_plural': 'Футер маалыматтары',
            },
        ),
    ]
