# Generated by Django 6.0.3 on 2026-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+996 553 414 929', max_length=50, verbose_name='Телефон номер')),
                ('email', models.EmailField(default='info@manastravel.kg', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='ул. Ленина 123, г. Джалал-Абад', max_length=255, verbose_name='Дарек')),
                ('work_hours', models.CharField(default='Пн - Сб: 09:00 – 18:00', max_length=150, verbose_name='Иштөө убактысы')),
                ('map_iframe_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2924.1234567890123!2d73.00000000000001!3d42.00000000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1234567890abcdef%3A0xabcdef1234567890!2sManas%20Travel%20Office!5e0!3m2!1sen!2skg!4v1700000000000', max_length=500, verbose_name='Google Maps iframe URL')),
                ('instagram_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Telegram')),
                ('facebook_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('vk_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='VK')),
            ],
            options={
                'verbose_name': 'Контакт баракчасы',
                'verbose_name_plural': 'Контакт баракчасы',
            },
        ),
    ]
