# Generated by Django 6.0.3 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Дарек'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_iframe_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps iframe URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='work_hours',
            field=models.CharField(max_length=150, verbose_name='Иштөө убактысы'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон номур (мис: +996 553 414 929)'),
        ),
    ]
