# Generated by Django 6.0.5 on 2026-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactpage_address_alter_contactpage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.IntegerField(max_length=13, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.IntegerField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='phone',
            field=models.IntegerField(max_length=13, verbose_name='Телефон номур (мис: +996 553 414 929)'),
        ),
    ]
