# Generated by Django 6.0.5 on 2026-05-27 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactpage_phone_alter_contactrequest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Телефон номери так 13 сан болушу керек жана тамга болбошу керек.', regex='^\\d{13}$')], verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Телефон номери так 13 сан болушу керек жана тамга болбошу керек.', regex='^\\d{13}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='footercontact',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Телефон номери так 13 сан болушу керек жана тамга болбошу керек.', regex='^\\d{13}$')], verbose_name='Телефон номур (мис: +996 553 414 929)'),
        ),
    ]
