# Generated by Django 6.0.3 on 2026-05-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turs', '0002_populartour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(verbose_name='Толук описание')),
                ('location', models.CharField(max_length=200, verbose_name='Локация')),
                ('max_people', models.PositiveIntegerField(default=12, verbose_name='Максималдуу адам саны')),
                ('day1_title', models.CharField(max_length=200, verbose_name='1-күн аталышы')),
                ('day1_desc', models.TextField(verbose_name='1-күн описание')),
                ('day2_title', models.CharField(blank=True, max_length=200, verbose_name='2-күн аталышы')),
                ('day2_desc', models.TextField(blank=True, verbose_name='2-күн описание')),
                ('day3_title', models.CharField(blank=True, max_length=200, verbose_name='3-күн аталышы')),
                ('day3_desc', models.TextField(blank=True, verbose_name='3-күн описание')),
                ('included', models.TextField(verbose_name='Эмнелер кирет (саптар боюнча)')),
                ('not_included', models.TextField(verbose_name='Эмнелер кирбейт (саптар боюнча)')),
                ('gallery_image1', models.ImageField(blank=True, upload_to='tour_gallery/', verbose_name='Галерея сүрөтү 1')),
                ('gallery_image2', models.ImageField(blank=True, upload_to='tour_gallery/', verbose_name='Галерея сүрөтү 2')),
                ('gallery_image3', models.ImageField(blank=True, upload_to='tour_gallery/', verbose_name='Галерея сүрөтү 3')),
                ('price_per_person', models.PositiveIntegerField(default=0, verbose_name='Баасы (сом/киши)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='turs.populartour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Турдун деталдары',
                'verbose_name_plural': 'Турдун деталдары',
            },
        ),
    ]
