# Generated by Django 6.0.3 on 2026-05-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_detail', '0001_initial'),
        ('turs', '0002_populartour'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөнү')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('people_count', models.PositiveIntegerField(default=1, verbose_name='Адам саны')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Каалаган дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Иштетилди')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turs.populartour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Брондлоо заявкасы',
                'verbose_name_plural': 'Брондлоо заявкалары',
                'ordering': ['-created_at'],
            },
        ),
    ]
