# Generated by Django 6.0.3 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_detail', '0002_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='included',
            field=models.TextField(verbose_name='Эмнелер кирет'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='not_included',
            field=models.TextField(verbose_name='Эмнелер кирбейт '),
        ),
    ]
