# Generated by Django 6.0.3 on 2026-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Аталышы')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Сүрөт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Галерея сүрөтү',
                'verbose_name_plural': 'Галерея сүрөттөрү',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
