# Generated by Django 6.0.3 on 2026-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=100, verbose_name='Акция тексти')),
                ('title', models.CharField(max_length=200, verbose_name='Турдун аты')),
                ('description', models.TextField(verbose_name='Кыскача түшүндүрмө')),
                ('price', models.IntegerField(verbose_name='Баасы ($ менен)')),
                ('image_url', models.URLField(max_length=500, verbose_name='Сүрөттүн шилтемеси (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүүбү?')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайддар',
            },
        ),
    ]
