# Generated by Django 6.0.3 on 2026-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Турдун аты')),
                ('duration', models.CharField(max_length=100, verbose_name='Убактысы (мис: 3 күн / 2 түн)')),
                ('description', models.TextField(verbose_name='Кыскача түшүндүрмө')),
                ('price', models.IntegerField(verbose_name='Баасы (сом менен)')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Турдун сүрөтү')),
                ('is_popular', models.BooleanField(default=True, verbose_name='Популярдуу тур катары көрсөтүлсүнбү?')),
            ],
            options={
                'verbose_name': 'Популярдуу тур',
                'verbose_name_plural': 'Популярдуу турлар',
            },
        ),
    ]
